### ISSUE TITLE
In and StdDraw

### ISSUE THREAD

**Issue by KI05** [krs131099/Bar_Chart_Racer#1]
Were In.java and StdDraw.java classes provided in the beginning of the assignment or are those just solutions provided by the authors?

**Comment by var-nan** [comment]
Yes, they were part of the standard library by Robert Sedgewick and Kevin Wayne. If you have used their custom installation setup, their standard library package will be downloaded automatically. If you didn't used their custom installation, you can download them [here](https://introcs.cs.princeton.edu/java/stdlib/)

Hope that helps.

**Comment by KI05** [comment]
Thank you
